export const SORT_FASHION = 'desc'
export const SORT_PARAM = 'score'
export const GET_SCORE = 'score'
export const GET_NAME = 'name'
export const GET_UUID = 'uuid'
export const GET_CCODE = 'countryCode'
